"""Small, coherent seed dataset for the Lazarus Neo4j graph."""

from __future__ import annotations

SEED_DATA = {
    "drugs": [
        {
            "drug_id": "DRUG-001",
            "name": "RX-782",
            "mechanism_of_action": "Selective JAK1 inhibition that dampens interferon-driven inflammation",
            "modality": "Small molecule",
            "development_stage": "Phase 2",
            "status": "Shelved",
            "failure_reason": "Insufficient efficacy in moderate asthma subgroup",
            "company": "Northstar Bio",
        },
        {
            "drug_id": "DRUG-002",
            "name": "Oncavaxib",
            "mechanism_of_action": "Oral PARP1/2 inhibition for DNA damage response modulation",
            "modality": "Small molecule",
            "development_stage": "Phase 2",
            "status": "Discontinued",
            "failure_reason": "Dose-limiting hematologic toxicity in ovarian cancer",
            "company": "HelixForge Therapeutics",
        },
        {
            "drug_id": "DRUG-003",
            "name": "Neuroquel",
            "mechanism_of_action": "Microglial CSF1R inhibition intended to reduce neuroinflammation",
            "modality": "Small molecule",
            "development_stage": "Phase 1b",
            "status": "Paused",
            "failure_reason": "Portfolio reprioritization after weak biomarker separation",
            "company": "CortexNova",
        },
        {
            "drug_id": "DRUG-004",
            "name": "Fibrosant",
            "mechanism_of_action": "TGF-beta receptor I blockade to reduce fibroblast activation",
            "modality": "Monoclonal antibody",
            "development_stage": "Phase 2",
            "status": "Terminated",
            "failure_reason": "No meaningful slowing of pulmonary function decline",
            "company": "BlueHarbor Pharma",
        },
        {
            "drug_id": "DRUG-005",
            "name": "Immunava",
            "mechanism_of_action": "Dual TIGIT checkpoint inhibition to restore exhausted T-cell activity",
            "modality": "Monoclonal antibody",
            "development_stage": "Phase 1/2",
            "status": "Shelved",
            "failure_reason": "Low response rate in refractory solid tumors",
            "company": "Asterion Oncology",
        },
    ],
    "diseases": [
        {
            "disease_id": "DIS-001",
            "name": "Asthma",
            "category": "Respiratory",
            "icd_code": "J45",
            "description": "Chronic inflammatory airway disease with variable airflow obstruction.",
        },
        {
            "disease_id": "DIS-002",
            "name": "Systemic Lupus Erythematosus",
            "category": "Autoimmune",
            "icd_code": "M32.9",
            "description": "Systemic autoimmune disease often driven by interferon signaling.",
        },
        {
            "disease_id": "DIS-003",
            "name": "Ovarian Cancer",
            "category": "Oncology",
            "icd_code": "C56.9",
            "description": "Malignant neoplasm of the ovary with frequent homologous recombination defects.",
        },
        {
            "disease_id": "DIS-004",
            "name": "Triple-Negative Breast Cancer",
            "category": "Oncology",
            "icd_code": "C50.919",
            "description": "Aggressive breast cancer subtype lacking ER, PR, and HER2 expression.",
        },
        {
            "disease_id": "DIS-005",
            "name": "Alzheimer's Disease",
            "category": "Neurology",
            "icd_code": "G30.9",
            "description": "Progressive neurodegenerative disorder with cognitive decline and neuroinflammation.",
        },
        {
            "disease_id": "DIS-006",
            "name": "Idiopathic Pulmonary Fibrosis",
            "category": "Pulmonology",
            "icd_code": "J84.112",
            "description": "Fibrotic interstitial lung disease with poor long-term prognosis.",
        },
        {
            "disease_id": "DIS-007",
            "name": "Chronic Graft-versus-Host Disease",
            "category": "Immunology",
            "icd_code": "D89.811",
            "description": "Immune-mediated multi-organ disease after allogeneic transplant.",
        },
        {
            "disease_id": "DIS-008",
            "name": "Pancreatic Cancer",
            "category": "Oncology",
            "icd_code": "C25.9",
            "description": "Aggressive solid tumor with limited treatment options and dense stroma.",
        },
    ],
    "targets": [
        {
            "target_id": "TAR-001",
            "name": "Janus Kinase 1",
            "symbol": "JAK1",
            "target_type": "Kinase",
            "organism": "Homo sapiens",
        },
        {
            "target_id": "TAR-002",
            "name": "Poly(ADP-ribose) polymerase 1",
            "symbol": "PARP1",
            "target_type": "DNA repair enzyme",
            "organism": "Homo sapiens",
        },
        {
            "target_id": "TAR-003",
            "name": "Colony stimulating factor 1 receptor",
            "symbol": "CSF1R",
            "target_type": "Receptor tyrosine kinase",
            "organism": "Homo sapiens",
        },
        {
            "target_id": "TAR-004",
            "name": "Transforming growth factor beta receptor 1",
            "symbol": "TGFBR1",
            "target_type": "Serine/threonine kinase receptor",
            "organism": "Homo sapiens",
        },
        {
            "target_id": "TAR-005",
            "name": "T-cell immunoreceptor with Ig and ITIM domains",
            "symbol": "TIGIT",
            "target_type": "Immune checkpoint receptor",
            "organism": "Homo sapiens",
        },
    ],
    "clinical_trials": [
        {
            "trial_id": "NCT-LAZ-001",
            "title": "RX-782 in uncontrolled moderate asthma",
            "phase": "Phase 2",
            "status": "Terminated",
            "enrollment": 148,
            "start_date": "2022-01-10",
            "end_date": "2023-11-02",
            "failure_reason": "Primary endpoint on exacerbation reduction not met",
            "sponsor": "Northstar Bio",
        },
        {
            "trial_id": "NCT-LAZ-002",
            "title": "Oncavaxib maintenance therapy in platinum-sensitive ovarian cancer",
            "phase": "Phase 2",
            "status": "Completed",
            "enrollment": 96,
            "start_date": "2021-05-14",
            "end_date": "2023-02-19",
            "failure_reason": "Hematologic toxicity limited durable dosing",
            "sponsor": "HelixForge Therapeutics",
        },
        {
            "trial_id": "NCT-LAZ-003",
            "title": "Neuroquel early Alzheimer's biomarker modulation study",
            "phase": "Phase 1b",
            "status": "Withdrawn",
            "enrollment": 42,
            "start_date": "2023-03-06",
            "end_date": "2024-01-12",
            "failure_reason": "Weak biomarker separation and strategic deprioritization",
            "sponsor": "CortexNova",
        },
        {
            "trial_id": "NCT-LAZ-004",
            "title": "Fibrosant in progressive idiopathic pulmonary fibrosis",
            "phase": "Phase 2",
            "status": "Terminated",
            "enrollment": 121,
            "start_date": "2020-09-01",
            "end_date": "2022-12-21",
            "failure_reason": "No benefit versus standard of care",
            "sponsor": "BlueHarbor Pharma",
        },
        {
            "trial_id": "NCT-LAZ-005",
            "title": "Immunava in refractory solid tumors",
            "phase": "Phase 1/2",
            "status": "Completed",
            "enrollment": 87,
            "start_date": "2022-06-18",
            "end_date": "2024-04-29",
            "failure_reason": "Low objective response rate in heavily pretreated patients",
            "sponsor": "Asterion Oncology",
        },
    ],
    "evidence": [
        {
            "evidence_id": "EVID-001",
            "title": "JAK1 blockade dampens interferon signatures in lupus-like disease",
            "source": "Preclinical paper",
            "source_ref": "PMID:9000001",
            "snippet": "Selective JAK1 inhibition lowered interferon-response genes and improved renal inflammation.",
            "confidence_score": 0.86,
            "url": "https://example.org/evidence/jak1-lupus",
            "published_date": "2021-08-14",
        },
        {
            "evidence_id": "EVID-002",
            "title": "Asthma trial summary for RX-782",
            "source": "Clinical trial registry",
            "source_ref": "NCT-LAZ-001",
            "snippet": "The study missed its primary endpoint despite favorable tolerability.",
            "confidence_score": 0.78,
            "url": "https://example.org/trials/nct-laz-001",
            "published_date": "2023-11-20",
        },
        {
            "evidence_id": "EVID-003",
            "title": "PARP sensitivity markers detected in a TNBC subset",
            "source": "Translational study",
            "source_ref": "PMID:9000002",
            "snippet": "DNA repair deficiency signatures suggest a PARP-responsive subgroup in TNBC.",
            "confidence_score": 0.83,
            "url": "https://example.org/evidence/parp-tnbc",
            "published_date": "2022-04-02",
        },
        {
            "evidence_id": "EVID-004",
            "title": "Ovarian cancer exposure limits for Oncavaxib",
            "source": "Clinical study report",
            "source_ref": "CSR-LAZ-002",
            "snippet": "Myelosuppression prevented sustained dose intensity in ovarian cancer patients.",
            "confidence_score": 0.75,
            "url": "https://example.org/reports/oncavaxib-ovarian",
            "published_date": "2023-03-08",
        },
        {
            "evidence_id": "EVID-005",
            "title": "Microglial CSF1R inhibition reduces synaptic pruning in tauopathy models",
            "source": "Preclinical paper",
            "source_ref": "PMID:9000003",
            "snippet": "CSF1R suppression normalized activated microglia and improved memory readouts.",
            "confidence_score": 0.8,
            "url": "https://example.org/evidence/csf1r-neuro",
            "published_date": "2023-01-17",
        },
        {
            "evidence_id": "EVID-006",
            "title": "CSF1R pathway implicated in chronic graft-versus-host disease macrophage activation",
            "source": "Mechanistic paper",
            "source_ref": "PMID:9000004",
            "snippet": "Macrophage-rich lesions in chronic GVHD showed enrichment of CSF1R signaling.",
            "confidence_score": 0.77,
            "url": "https://example.org/evidence/csf1r-cgvhd",
            "published_date": "2024-02-06",
        },
        {
            "evidence_id": "EVID-007",
            "title": "TGF-beta blockade attenuates fibroblast activation in pancreatic cancer stroma",
            "source": "Preclinical paper",
            "source_ref": "PMID:9000005",
            "snippet": "TGF-beta receptor inhibition reduced collagen deposition and improved immune infiltration.",
            "confidence_score": 0.79,
            "url": "https://example.org/evidence/tgfbr1-pancreas",
            "published_date": "2022-09-28",
        },
        {
            "evidence_id": "EVID-008",
            "title": "Fibrosant IPF termination summary",
            "source": "Clinical trial registry",
            "source_ref": "NCT-LAZ-004",
            "snippet": "No clinically meaningful slowing of FVC decline was observed in IPF.",
            "confidence_score": 0.74,
            "url": "https://example.org/trials/nct-laz-004",
            "published_date": "2022-12-30",
        },
        {
            "evidence_id": "EVID-009",
            "title": "TIGIT-high immune exhaustion phenotype in pancreatic cancer",
            "source": "Tumor immunology study",
            "source_ref": "PMID:9000006",
            "snippet": "Pancreatic tumors showed TIGIT enrichment on dysfunctional T cells resistant to PD-1 monotherapy.",
            "confidence_score": 0.81,
            "url": "https://example.org/evidence/tigit-pancreas",
            "published_date": "2024-05-15",
        },
        {
            "evidence_id": "EVID-010",
            "title": "Immunava solid tumor program debrief",
            "source": "Investor update",
            "source_ref": "IR-LAZ-005",
            "snippet": "Broad solid tumor enrollment diluted signal and masked a pancreas-enriched checkpoint biology story.",
            "confidence_score": 0.68,
            "url": "https://example.org/reports/immunava-solid-tumor",
            "published_date": "2024-06-01",
        },
    ],
    "repurposing_hypotheses": [
        {
            "hypothesis_id": "HYP-001",
            "title": "Reposition RX-782 from asthma to lupus",
            "summary": "RX-782 failed in asthma but its JAK1 biology aligns better with interferon-driven lupus pathology.",
            "status": "Candidate",
            "advocate_score": 0.88,
            "skeptic_score": 0.31,
            "judge_score": 0.79,
            "final_confidence": 0.82,
            "created_at": "2026-04-17T09:00:00Z",
        },
        {
            "hypothesis_id": "HYP-002",
            "title": "Repurpose Oncavaxib for TNBC biomarker-selected patients",
            "summary": "Despite ovarian toxicity limits, Oncavaxib may still fit a narrower TNBC DNA repair deficient subgroup.",
            "status": "Candidate",
            "advocate_score": 0.76,
            "skeptic_score": 0.44,
            "judge_score": 0.7,
            "final_confidence": 0.69,
            "created_at": "2026-04-17T09:05:00Z",
        },
        {
            "hypothesis_id": "HYP-003",
            "title": "Redirect Neuroquel to chronic GVHD macrophage biology",
            "summary": "Neuroquel's CSF1R mechanism may be more tractable in chronic GVHD than Alzheimer's disease.",
            "status": "Candidate",
            "advocate_score": 0.73,
            "skeptic_score": 0.39,
            "judge_score": 0.68,
            "final_confidence": 0.67,
            "created_at": "2026-04-17T09:10:00Z",
        },
        {
            "hypothesis_id": "HYP-004",
            "title": "Move Fibrosant from IPF into pancreatic cancer stroma modulation",
            "summary": "Fibrosant underperformed in diffuse fibrosis but may help remodel pancreatic tumor stroma.",
            "status": "Candidate",
            "advocate_score": 0.72,
            "skeptic_score": 0.42,
            "judge_score": 0.66,
            "final_confidence": 0.65,
            "created_at": "2026-04-17T09:15:00Z",
        },
        {
            "hypothesis_id": "HYP-005",
            "title": "Focus Immunava on TIGIT-high pancreatic cancer",
            "summary": "Immunava may recover value in a TIGIT-enriched pancreatic cancer setting instead of basket solid tumors.",
            "status": "Candidate",
            "advocate_score": 0.78,
            "skeptic_score": 0.41,
            "judge_score": 0.71,
            "final_confidence": 0.72,
            "created_at": "2026-04-17T09:20:00Z",
        },
    ],
    "relationships": {
        "drug_failed_for": [
            {"drug_id": "DRUG-001", "disease_id": "DIS-001"},
            {"drug_id": "DRUG-002", "disease_id": "DIS-003"},
            {"drug_id": "DRUG-003", "disease_id": "DIS-005"},
            {"drug_id": "DRUG-004", "disease_id": "DIS-006"},
            {"drug_id": "DRUG-005", "disease_id": "DIS-008"},
        ],
        "drug_originally_indicated_for": [
            {"drug_id": "DRUG-001", "disease_id": "DIS-001"},
            {"drug_id": "DRUG-002", "disease_id": "DIS-003"},
            {"drug_id": "DRUG-003", "disease_id": "DIS-005"},
            {"drug_id": "DRUG-004", "disease_id": "DIS-006"},
            {"drug_id": "DRUG-005", "disease_id": "DIS-008"},
        ],
        "drug_targets": [
            {"drug_id": "DRUG-001", "target_id": "TAR-001"},
            {"drug_id": "DRUG-002", "target_id": "TAR-002"},
            {"drug_id": "DRUG-003", "target_id": "TAR-003"},
            {"drug_id": "DRUG-004", "target_id": "TAR-004"},
            {"drug_id": "DRUG-005", "target_id": "TAR-005"},
        ],
        "drug_tested_in": [
            {"drug_id": "DRUG-001", "trial_id": "NCT-LAZ-001"},
            {"drug_id": "DRUG-002", "trial_id": "NCT-LAZ-002"},
            {"drug_id": "DRUG-003", "trial_id": "NCT-LAZ-003"},
            {"drug_id": "DRUG-004", "trial_id": "NCT-LAZ-004"},
            {"drug_id": "DRUG-005", "trial_id": "NCT-LAZ-005"},
        ],
        "trial_for_disease": [
            {"trial_id": "NCT-LAZ-001", "disease_id": "DIS-001"},
            {"trial_id": "NCT-LAZ-002", "disease_id": "DIS-003"},
            {"trial_id": "NCT-LAZ-003", "disease_id": "DIS-005"},
            {"trial_id": "NCT-LAZ-004", "disease_id": "DIS-006"},
            {"trial_id": "NCT-LAZ-005", "disease_id": "DIS-008"},
        ],
        "drug_supported_by": [
            {"drug_id": "DRUG-001", "evidence_id": "EVID-001"},
            {"drug_id": "DRUG-001", "evidence_id": "EVID-002"},
            {"drug_id": "DRUG-002", "evidence_id": "EVID-003"},
            {"drug_id": "DRUG-002", "evidence_id": "EVID-004"},
            {"drug_id": "DRUG-003", "evidence_id": "EVID-005"},
            {"drug_id": "DRUG-003", "evidence_id": "EVID-006"},
            {"drug_id": "DRUG-004", "evidence_id": "EVID-007"},
            {"drug_id": "DRUG-004", "evidence_id": "EVID-008"},
            {"drug_id": "DRUG-005", "evidence_id": "EVID-009"},
            {"drug_id": "DRUG-005", "evidence_id": "EVID-010"},
        ],
        "disease_supported_by": [
            {"disease_id": "DIS-001", "evidence_id": "EVID-002"},
            {"disease_id": "DIS-002", "evidence_id": "EVID-001"},
            {"disease_id": "DIS-003", "evidence_id": "EVID-004"},
            {"disease_id": "DIS-004", "evidence_id": "EVID-003"},
            {"disease_id": "DIS-005", "evidence_id": "EVID-005"},
            {"disease_id": "DIS-007", "evidence_id": "EVID-006"},
            {"disease_id": "DIS-006", "evidence_id": "EVID-008"},
            {"disease_id": "DIS-008", "evidence_id": "EVID-007"},
            {"disease_id": "DIS-008", "evidence_id": "EVID-009"},
        ],
        "target_supported_by": [
            {"target_id": "TAR-001", "evidence_id": "EVID-001"},
            {"target_id": "TAR-002", "evidence_id": "EVID-003"},
            {"target_id": "TAR-003", "evidence_id": "EVID-005"},
            {"target_id": "TAR-003", "evidence_id": "EVID-006"},
            {"target_id": "TAR-004", "evidence_id": "EVID-007"},
            {"target_id": "TAR-005", "evidence_id": "EVID-009"},
        ],
        "clinical_trial_supported_by": [
            {"trial_id": "NCT-LAZ-001", "evidence_id": "EVID-002"},
            {"trial_id": "NCT-LAZ-002", "evidence_id": "EVID-004"},
            {"trial_id": "NCT-LAZ-003", "evidence_id": "EVID-005"},
            {"trial_id": "NCT-LAZ-004", "evidence_id": "EVID-008"},
            {"trial_id": "NCT-LAZ-005", "evidence_id": "EVID-010"},
        ],
        "hypothesis_proposes_repurposing_of": [
            {"hypothesis_id": "HYP-001", "drug_id": "DRUG-001"},
            {"hypothesis_id": "HYP-002", "drug_id": "DRUG-002"},
            {"hypothesis_id": "HYP-003", "drug_id": "DRUG-003"},
            {"hypothesis_id": "HYP-004", "drug_id": "DRUG-004"},
            {"hypothesis_id": "HYP-005", "drug_id": "DRUG-005"},
        ],
        "hypothesis_from_disease": [
            {"hypothesis_id": "HYP-001", "disease_id": "DIS-001"},
            {"hypothesis_id": "HYP-002", "disease_id": "DIS-003"},
            {"hypothesis_id": "HYP-003", "disease_id": "DIS-005"},
            {"hypothesis_id": "HYP-004", "disease_id": "DIS-006"},
            {"hypothesis_id": "HYP-005", "disease_id": "DIS-008"},
        ],
        "hypothesis_to_disease": [
            {"hypothesis_id": "HYP-001", "disease_id": "DIS-002"},
            {"hypothesis_id": "HYP-002", "disease_id": "DIS-004"},
            {"hypothesis_id": "HYP-003", "disease_id": "DIS-007"},
            {"hypothesis_id": "HYP-004", "disease_id": "DIS-008"},
            {"hypothesis_id": "HYP-005", "disease_id": "DIS-008"},
        ],
        "hypothesis_based_on_target": [
            {"hypothesis_id": "HYP-001", "target_id": "TAR-001"},
            {"hypothesis_id": "HYP-002", "target_id": "TAR-002"},
            {"hypothesis_id": "HYP-003", "target_id": "TAR-003"},
            {"hypothesis_id": "HYP-004", "target_id": "TAR-004"},
            {"hypothesis_id": "HYP-005", "target_id": "TAR-005"},
        ],
        "hypothesis_supported_by": [
            {"hypothesis_id": "HYP-001", "evidence_id": "EVID-001"},
            {"hypothesis_id": "HYP-001", "evidence_id": "EVID-002"},
            {"hypothesis_id": "HYP-002", "evidence_id": "EVID-003"},
            {"hypothesis_id": "HYP-002", "evidence_id": "EVID-004"},
            {"hypothesis_id": "HYP-003", "evidence_id": "EVID-005"},
            {"hypothesis_id": "HYP-003", "evidence_id": "EVID-006"},
            {"hypothesis_id": "HYP-004", "evidence_id": "EVID-007"},
            {"hypothesis_id": "HYP-004", "evidence_id": "EVID-008"},
            {"hypothesis_id": "HYP-005", "evidence_id": "EVID-009"},
            {"hypothesis_id": "HYP-005", "evidence_id": "EVID-010"},
        ],
    },
}
