export const NODE_THEME = {
  Drug: {
    color: '#2563eb',
    border: '#1d4ed8',
    shape: 'round-rectangle',
    overlay: '#dbeafe',
  },
  Target: {
    color: '#f59e0b',
    border: '#d97706',
    shape: 'diamond',
    overlay: '#fef3c7',
  },
  Disease: {
    color: '#16a34a',
    border: '#15803d',
    shape: 'round-rectangle',
    overlay: '#dcfce7',
  },
  Evidence: {
    color: '#7c3aed',
    border: '#6d28d9',
    shape: 'triangle',
    overlay: '#ede9fe',
  },
  Hypothesis: {
    color: '#ef4444',
    border: '#b91c1c',
    shape: 'star',
    overlay: '#fee2e2',
  },
  Strategy: {
    color: '#1e293b',
    border: '#0f172a',
    shape: 'hexagon',
    overlay: '#dbe4f0',
  },
}

export const EDGE_THEME = {
  TARGETS: '#2563eb',
  FAILED_FOR: '#9b3d3d',
  ORIGINALLY_INDICATED_FOR: '#64748b',
  SUPPORTED_BY: '#7c3aed',
  PROPOSES_REPURPOSING_OF: '#ef4444',
  TO_DISEASE: '#16a34a',
  BASED_ON_TARGET: '#f59e0b',
  RECOMMENDS: '#1e293b',
  LINKED_TO: '#0f766e',
  RELATED_TO: '#94a3b8',
}

export const baseGraphStylesheet = [
  {
    selector: 'node',
    style: {
      label: 'data(label)',
      'background-color': '#cbd5e1',
      'border-color': '#94a3b8',
      shape: 'ellipse',
      color: '#0f172a',
      'font-size': 13,
      'font-weight': 600,
      'text-wrap': 'wrap',
      'text-max-width': 96,
      'text-valign': 'bottom',
      'text-margin-y': 16,
      'text-halign': 'center',
      'text-outline-width': 4,
      'text-outline-color': '#ffffff',
      'text-background-color': '#ffffff',
      'text-background-opacity': 0.92,
      'text-background-padding': 4,
      'text-border-color': '#e2e8f0',
      'text-border-width': 1,
      'min-zoomed-font-size': 9,
      'border-width': 2,
      width: 52,
      height: 52,
      'overlay-opacity': 0,
      'z-index': 10,
      'transition-property': 'background-color, border-color, width, height, opacity',
      'transition-duration': '220ms',
    },
  },
  {
    selector: 'edge',
    style: {
      label: 'data(label)',
      width: 2,
      'line-color': '#cbd5e1',
      'target-arrow-color': '#cbd5e1',
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      'arrow-scale': 0.85,
      color: '#334155',
      'font-size': 11,
      'font-weight': 700,
      'text-background-color': '#ffffff',
      'text-background-opacity': 1,
      'text-background-padding': 5,
      'text-border-color': '#e2e8f0',
      'text-border-width': 1,
      'text-border-opacity': 1,
      'text-rotation': 'none',
      'text-margin-y': -10,
      'text-wrap': 'wrap',
      'text-max-width': 110,
      'text-events': 'yes',
      'min-zoomed-font-size': 8,
      'z-index': 2,
      opacity: 0.88,
      'transition-property': 'line-color, target-arrow-color, width, opacity, color',
      'transition-duration': '220ms',
    },
  },
  {
    selector: 'node[nodeType = "Drug"]',
    style: {
      'background-color': NODE_THEME.Drug.color,
      'border-color': NODE_THEME.Drug.border,
      shape: NODE_THEME.Drug.shape,
      width: 68,
      height: 42,
    },
  },
  {
    selector: 'node[nodeType = "Target"]',
    style: {
      'background-color': NODE_THEME.Target.color,
      'border-color': NODE_THEME.Target.border,
      shape: NODE_THEME.Target.shape,
      width: 52,
      height: 52,
    },
  },
  {
    selector: 'node[nodeType = "Disease"]',
    style: {
      'background-color': NODE_THEME.Disease.color,
      'border-color': NODE_THEME.Disease.border,
      shape: NODE_THEME.Disease.shape,
      width: 62,
      height: 38,
    },
  },
  {
    selector: 'node[nodeType = "Evidence"]',
    style: {
      'background-color': NODE_THEME.Evidence.color,
      'border-color': NODE_THEME.Evidence.border,
      shape: NODE_THEME.Evidence.shape,
      width: 48,
      height: 48,
    },
  },
  {
    selector: 'node[nodeType = "Hypothesis"]',
    style: {
      'background-color': NODE_THEME.Hypothesis.color,
      'border-color': NODE_THEME.Hypothesis.border,
      shape: NODE_THEME.Hypothesis.shape,
      width: 64,
      height: 64,
      'shadow-blur': 18,
      'shadow-color': '#fca5a5',
      'shadow-opacity': 0.5,
    },
  },
  {
    selector: 'node[nodeType = "Strategy"]',
    style: {
      'background-color': NODE_THEME.Strategy.color,
      'border-color': NODE_THEME.Strategy.border,
      shape: NODE_THEME.Strategy.shape,
      width: 62,
      height: 56,
      color: '#0f172a',
    },
  },
  {
    selector: 'node.is-stage-active',
    style: {
      'border-width': 4,
      'shadow-blur': 20,
      'shadow-color': '#22c55e',
      'shadow-opacity': 0.35,
      'z-index': 12,
    },
  },
  {
    selector: 'node.is-related',
    style: {
      'border-width': 3,
      opacity: 1,
    },
  },
  {
    selector: 'node.is-selected',
    style: {
      'border-width': 5,
      'shadow-blur': 24,
      'shadow-color': '#0f172a',
      'shadow-opacity': 0.28,
      'z-index': 16,
    },
  },
  {
    selector: 'node.is-hovered',
    style: {
      'border-width': 4,
      'shadow-blur': 16,
      'shadow-opacity': 0.25,
    },
  },
  {
    selector: 'node.is-dim',
    style: {
      opacity: 0.2,
      'text-opacity': 0.24,
    },
  },
  {
    selector: 'edge.is-stage-edge',
    style: {
      width: 4,
      'line-color': '#22c55e',
      'target-arrow-color': '#22c55e',
      color: '#14532d',
      'text-background-color': '#f0fdf4',
      'text-border-color': '#86efac',
      opacity: 1,
      'z-index': 8,
    },
  },
  {
    selector: 'edge.is-related',
    style: {
      width: 3.5,
      opacity: 1,
      'line-color': '#0f766e',
      'target-arrow-color': '#0f766e',
      color: '#134e4a',
      'text-background-color': '#f0fdfa',
      'text-border-color': '#99f6e4',
    },
  },
  {
    selector: 'edge.is-hovered',
    style: {
      width: 4,
      opacity: 1,
      'line-color': '#1d4ed8',
      'target-arrow-color': '#1d4ed8',
      color: '#1e3a8a',
      'text-background-color': '#eff6ff',
      'text-border-color': '#93c5fd',
    },
  },
  {
    selector: 'edge.is-dim',
    style: {
      opacity: 0.12,
      'text-opacity': 0.18,
    },
  },
]

export function edgeColorForRelationship(relationship) {
  return EDGE_THEME[relationship] ?? EDGE_THEME.RELATED_TO
}
